#+TITLE: Пишем интерпретатор Scheme за 48 часов: боевое введение в Haskell
#+ENCODING: KOI8-R
#+LANGUAGE: RU
#+AUTHOR: Jonathan Tang

*Краткое вступление*

Большинство учебников по Haskell в интернете больше похожи на
справочники. Они описывают синтаксис языка, некоторые его конструкции,
и некоторые простые функции для работы с командной строкой. А вот о
том, как писать функциональные, полезные программы, упоминается в
конце, а иногда и вообще опускается.

У этого учебника другой подход. Вы начнёте с изучения аргументов
командной строки и их разбора, и дойдёте до написания
полнофункционального интерпретатора языка программирования Scheme, в
котором будет реализовано большое подмножество [[http://www.schemers.org/Documents/Standards/R5RS/HTML][R5RS Scheme]] А по ходу
вы изучите систему ввода/вывода, mutable state, динамическую
типизацию, обработку ошибок, и разбор текстов. А когда вы закончите,
вы достаточно свободно будете владеть и Haskell, и Scheme.

Учебник предназначен для тех:
1. кто уже знает Лисп (особенно диалект Scheme) и хочет изучить
   Haskell;
2. кто не владеет ни одним языком программирования, но имеет большой
   запас базовых знаний и знаком с компьютерами.

Тем, кто использует процедурные и объектно-ориентированные языки
(такие как C, Java, Python), следует забыть многое, что вы уже знаете
о программировании. Haskell очень сильно отличается от этих языков, и
требует совершенно другого образа мышления при написании
программ. Будет лучше, если вы начнёте изучать это руководство с
чистого листа, и не будете пытаться сравнивать Haskell с императивными
языками, потому как многие концепции в них (классы, функции, 'return')
имеют совершенно иные значения в Haskell.

Каждый урок использует код, написанный в предыдущих главах. Поэтому
уроки следует изучать по порядку.

Мы подразумеваем, что вы используете [[http://www.haskell.org/ghc/][GHC]] в качестве компилятора. Вы
также можете использовать [[http://www.haskell.org/hugs/][Hugs]] , но, возможно, для него вам придется
скачать дополнительные библиотеки.

Исходные коды из учебника доступны здесь: [[http://jonathan.tang.name/files/scheme_in_48/code/][исходные коды]].

#+INCLUDE: "./chapters/chapter1.org" org-mode :minlevel 1
#+INCLUDE: "./chapters/chapter2.org" org-mode :minlevel 1
#+INCLUDE: "./chapters/chapter3.org" org-mode :minlevel 1
#+INCLUDE: "./chapters/chapter4.org" org-mode :minlevel 1
#+INCLUDE: "./chapters/chapter5.org" org-mode :minlevel 1
# #+INCLUDE: "./chapters/chapter6.org" org-mode :minlevel 1
# #+INCLUDE: "./chapters/chapter7.org" org-mode :minlevel 1
# #+INCLUDE: "./chapters/chapter8.org" org-mode :minlevel 1
# #+INCLUDE: "./chapters/chapter9.org" org-mode :minlevel 1
# #+INCLUDE: "./chapters/chapter10.org" org-mode :minlevel 1
# #+INCLUDE: "./appendix/apA.org" org-mode :minlevel 1
# #+INCLUDE: "./appendix/apB.org" org-mode :minlevel 1
# #+INCLUDE: "./appendix/apC.org" org-mode :minlevel 1
# #+INCLUDE: "./appendix/apD.org" org-mode :minlevel 1
